image: node:18.13.0

stages:
  - build
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - lib-docs/node_modules/

variables:
  NODE_ENV: production

build-docs:
  stage: build
  before_script:
    - rm -rf lib-docs/node_modules lib-docs/package-lock.json
  script:
    - cd lib-docs
    - npm install --no-optional
    - npm run build
    - npm run generate
  artifacts:
    paths:
      - lib-docs/.output/public
  only:
    - dev

pages:
  stage: deploy
  dependencies:
    - build-docs
  script:
    - mv lib-docs/.output/public public/
    - ls -l public
  artifacts:
    paths:
      - public/
  only:
    - dev
