image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build-docs:
  stage: build
  script:
    - cd lib-docs
    - npm install
    - npm run build
    - npm run generate
  artifacts:
    paths:
      - lib-docs/dist
  only:
    - dev

deploy-docs:
  stage: deploy
  script:
    - cd lib-docs
    - mv public lib-docs
  artifacts:
    paths:
      - lib-docs
  only:
    - dev
